networks:
  dev:

services:

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/base/static
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api
    image: api_v1.001
    volumes:
      - static_volume:/app/base/static
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - dev
  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata16:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - 5432:5432
    networks:
      - dev


  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: celery_worker
    # Переопределяем команду запуска — вместо gunicorn запускаем worker
    command: celery -A base worker -l info  # ← замени myproject на имя твоего проекта
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - db
    networks:
      - dev

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: celery_beat
    # Beat — планировщик, запускает задачи по расписанию
    command: celery -A base beat -l info  # ← замени myproject на имя твоего проекта
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - db
    networks:
      - dev


  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - dev


volumes:
  static_volume:
  pgdata16: