version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"


  # frontend:
  #   build: ./frontend
  #   container_name: vue_app
  #   restart: always
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend

  telegram_bot:
    build: ./bot
    container_name: telegram_bot
    restart: always
    volumes:
      - ./bot:/app
    env_file:
      - ./.env.dev

  redis:
      image: redis:7.0.5-alpine
      hostname: redis


volumes:
  postgres_data: