# Ограничить Redis только локальным интерфейсом внутри Docker сети
# Если вы не используете host network mode или не биндите его к внешнему IP напрямую
bind 0.0.0.0

protected-mode yes

requirepass befd2bc28866e973e7ce

rename-command CONFIG ""

# Опционально: настройте лимит на количество одновременных подключений
maxclients 1000