# Generated by Django 5.0.1 on 2026-07-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='Черный список')),
                ('blacklist_reason', models.TextField(blank=True)),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='Неявок')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_completed_orders', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Создана бронь'), ('order_completed', 'Получил валюту'), ('order_cancelled', 'Отмена'), ('no_show', 'Не пришёл'), ('blacklist', 'В чёрный список'), ('whitelist', 'Разблокирован'), ('comment', 'Комментарий')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.clientprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crm.clienttag'),
        ),
    ]
