# Generated by Django 5.0.1 on 2026-03-03 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('currency', '0004_exchanger_slug_exchanger_work_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[
                 ('desk', 'Касса'), ('car', 'Машина инкассации')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange_point', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='currency.exchanger')),
            ],
            options={
                'verbose_name': 'Оптовая касса',
                'verbose_name_plural': 'Оптовые кассы',
                'ordering': ['exchange_point'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[
                 ('in', 'Приход'), ('out', 'Расход')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='currency.currency', verbose_name='Валюта')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='movements', to='wholesale.cashnode', verbose_name='Касса')),
            ],
            options={
                'verbose_name': 'Движение средств',
                'verbose_name_plural': 'История движений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[
                 ('cashier', 'Кассир'), ('collector', 'Инкассатор'), ('senior', 'Старший')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('nodes', models.ManyToManyField(blank=True, null=True,
                 to='wholesale.cashnode', verbose_name='Доступные кассы')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(
                    default=True, verbose_name='Открыть смену')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='shifts', to='wholesale.cashnode', verbose_name='Касса')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='shifts', to='wholesale.staffprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[
                 ('buy', 'Покупка'), ('sell', 'Продажа'), ('in', 'Приход'), ('out', 'Расход')], max_length=10)),
                ('amount_currency', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сума')),
                ('rate', models.DecimalField(blank=True, decimal_places=4,
                 max_digits=12, null=True, verbose_name='Курс')),
                ('old_currency', models.BooleanField(
                    default=False, verbose_name='Ветхая купюра')),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=18, null=True, verbose_name='Еквівалент')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='currency.currency', verbose_name='Валюта')),
                ('shift', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wholesale.shift')),
            ],
            options={
                'verbose_name': 'Обмен валют',
                'verbose_name_plural': 'Обмен валют',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2,
                 default=0, max_digits=18, verbose_name='Остаток')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='balances', to='currency.currency', verbose_name='Валюта')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='balances', to='wholesale.cashnode', verbose_name='Касса')),
            ],
            options={
                'verbose_name': 'Баланс кассы',
                'verbose_name_plural': 'Балансы касс',
                'ordering': ['currency'],
                'unique_together': {('node', 'currency')},
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(
                ('is_open', True)), fields=('staff',), name='unique_open_shift_per_staff'),
        ),
    ]
