# Generated by Django 5.0.1 on 2026-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='wholesale.cashnode', verbose_name='Доступные кассы'),
        ),
    ]
