# Generated by Django 5.0.1 on 2026-04-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currency_is_cross_currency_currency_short_name_and_more'),
        ('wholesale', '0002_staffprofile_telephone_alter_staffprofile_nodes'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='wholesaleorder',
        #     name='old_currency',
        # ),
        migrations.AddField(
            model_name='shift',
            name='morning_balances',
            field=models.JSONField(blank=True, null=True,
                                   verbose_name='Утренний баланс'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='base_orders', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Сторно'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='profit',
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Прибуль'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), (
                'buy', '⬇ Покупка'), ('sell', '⬆ Продажа'), ('reversal', 'Сторно')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cashnode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('collector', 'Инкассатор'), (
                'senior', 'Старший')], max_length=20, verbose_name='Роль'),
        ),
    ]
