# Generated by Django 5.0.1 on 2026-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_repair_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleorder',
            name='old_currency',
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('buy', '⬇ Покупка'), ('sell', '⬆ Продажа'), (
                'collect', 'Инкассация'), ('add', 'Подкрепление'), ('reversal', 'Сторно')], max_length=20),
        ),
    ]
