# Generated by Django 5.0.1 on 2026-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_remove_wholesaleorder_old_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleorder',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('in', 'Приход'), (
                'out', 'Расход'), ('collect', 'Инкассация'), ('add', 'Подкрепление')], max_length=20),
        ),
    ]
