# Generated by Django 5.0.1 on 2025-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('currency',), 'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('id',), 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='exchanger',
            options={'ordering': ('id',), 'verbose_name': 'Обменик', 'verbose_name_plural': 'Все Обменики'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='users',
            name='clients_telephone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='buy',
            field=models.CharField(max_length=10, verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sell',
            field=models.CharField(max_length=10, verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
