# Generated by Django 5.0.1 on 2025-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_cartitem_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['sort_order', 'name'],
                     'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AddField(
            model_name='currency',
            name='is_visible',
            field=models.BooleanField(
                default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sort_order',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
