# Generated by Django 5.0.1 on 2026-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_options_currency_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_cross_currency',
            field=models.BooleanField(default=False, help_text='Использовать ли эту валюту для кросс-курсов', verbose_name='Кросс-валюта'),
        ),
        migrations.AddField(
            model_name='currency',
            name='short_name',
            field=models.CharField(blank=True, help_text='Например: $, €, грн', max_length=10, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='work_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='work_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchanger',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
